name: Counselling and Therapy
favicon: null
layout_spectrum: 0.804283824050799
typography_spectrum: 0.30481200525537133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9378309294115752
  lightness: 0.9862975380383432
  saturation: 0.928745811805129
  rhythmicContrast: 0.47976747737266123
purpose: []
